project_name: example
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
changelog:
  sort: asc
