name: greeting-action-trial

on: pull_request_target

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: mertssmnoglu/greeting-action@deauth
      with:
        message: "This is a test message. I hope it works."
