name: Releaser
run-name: release

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "Hello world"
